version: '3'

services:
  mev-commit-bidder:
    build: .
    environment:
      DOMAIN: ${DOMAIN}
      PRIVATE_KEY_BIDDER: ${PRIVATE_KEY_BIDDER}
      AUTO_DEPOSIT_VALUE: ${AUTO_DEPOSIT_VALUE}
    networks:
      - app-network
    ports:
      - "13524:13524" 
      - "13523:13523"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS=env:bidder-bot
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:datadog/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    depends_on:
      - mev-commit-bidder
    networks:
      - app-network 

networks:
  app-network:
    external: true

volumes:
  grafana-data:
  prometheus-data:
